project:
  type: website
  output-dir: docs

website:
  title: "EZ Data Lab"
  favicon: favicon.png
  navbar:
    left:
      - text: 'Home'
        href: index.html
      - about.qmd
    right:
      - icon: github
        href: https://github.com/Edgar-Zamora
      - icon: linkedin
        href: https://www.linkedin.com/in/edgar-zamora-01896b148/
format:
  html:
    theme: 
      dark: darkly
      light: flatly
    css: styles.css

editor: visual

